### ISSUE TITLE
Mapdb items

### ISSUE THREAD

**Issue by patrizioperrone** [massimilianocasini/rmproject1#79]
Massimiliano gli item da includere in mapdb per il momento sono. Metti una frequenza di 10 minuti.

VMC_Abilitazione_Forzatura_Deumidifica_CS14
VMC_Abilitazione_Forzatura_Trattamento_CS11
VMC_Forzatura_Deumidifica_CS15
VMC_Forzatura_Off_Trattamento_CS2
VMC_Forzatura_Raffreddamento_CS13
VMC_Forzatura_Riscaldamento_CS12
VMC_Set_Ricambio_HR2
VMC_Set_Temperatura_Effettivo_IR20
VMC_Set_Umidita_Effettivo_IR21
VMC_Stagione_CS1
VMC_ON_OFF_CS0
VMC_AUTO_MODE
VMC_Set_Temperatura_Ambiente_HR0
VMC_Set_Temperatura_Massima_Estiva_HR12
VMC_Set_Temperatura_Minima_Invernale_HR11
VMC_Set_Umidita_Relativa_Ambiente_HR1
pixsysIn1
AUTO_MANUAL_TANKS_FILLING

**Comment by massimilianocasini** [comment]
Tutti gli items creati da PaperUI devono essere gestiti da PaperUI quindi va aggiunto ad ogni item il gruppo gMapDb che ho creato.
Per pixsysIn1 è già stato inserito su file.
